# Generated by Django 3.2 on 2022-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_has_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="has_sizes",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
